apiVersion: v1
kind: Service
metadata:
  name: {{ include "sat-image-changes.fullname" . }}-frontend
  labels:
    {{- include "sat-image-changes.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.frontend.service.portWeb }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sat-image-changes.selectorLabels" . | nindent 4 }}
    component: frontend
