apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sat-image-changes.fullname" . }}-frontend
  labels:
    {{- include "sat-image-changes.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount | default .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sat-image-changes.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "sat-image-changes.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.portWeb }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
